#!/bin/bash
# postinst script for indi-mqtt

# enable and start service
if [ -x /run/systemd/system ]; then
    sudo systemctl daemon-reload
    systemctl enable astroberry-mqtt.service
    systemctl start astroberry-mqtt.service
fi
